# Generated by Django 5.2.6 on 2026-02-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_subject_enrollment_marks_markshistory_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='external',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='internal',
            field=models.FloatField(default=0),
        ),
    ]
