# Generated by Django 5.2.6 on 2026-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_marks_external_marks_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_project',
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('Sem1', 'Semester 1'), ('Sem2', 'Semester 2')], default='Sem1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('INTERNSHIP', 'Internship'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
