# Generated by Django 5.2.6 on 2026-02-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_student_section_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_scheme',
            field=models.CharField(choices=[('MID20', 'Mid 20 (Best 2)'), ('MID15_AT4', 'Mid 15 + AT 4'), ('MID40', 'Mid 40 (Best 2 Avg)'), ('EST100', 'Only EST 100'), ('LAB', 'Internal + External'), ('INTERNSHIP', 'External Only')], default='MID20', max_length=30),
        ),
    ]
