# Generated by Django 5.2.6 on 2026-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_subject_exam_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='exam_scheme',
            field=models.CharField(blank=True, choices=[('MID20', 'Mid 20 (Best 2)'), ('MID15_AT4', 'Mid 15 + AT 4'), ('MID40', 'Mid 40 (Best 2 Avg)'), ('EST100', 'Only EST 100'), ('LAB', 'Internal + External'), ('INTERNSHIP', 'External Only')], max_length=30, null=True),
        ),
    ]
