# Generated by Django 5.2.6 on 2026-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_subject_exam_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='regulation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
