# Generated by Django 5.2.6 on 2026-02-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_subject_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'regulation', 'level', 'semester', 'branch')},
        ),
    ]
