# Generated by Django 5.2.6 on 2026-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_subject_code_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('AIML', 'AIML'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CHEM', 'CHEM'), ('MME', 'MME')], max_length=20, null=True),
        ),
    ]
