# Generated by Django 5.2.6 on 2026-02-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MARK_UPDATE', 'Mark Update'), ('BATCH_PROMOTE', 'Batch Promote'), ('BATCH_CREATE', 'Batch Create'), ('BATCH_COMPLETE', 'Batch Complete'), ('SUBJECT_CREATE', 'Subject Create'), ('PDF_EXPORT', 'PDF Export'), ('BULK_UPLOAD', 'Bulk Upload'), ('NOTIFICATION', 'Notification')], max_length=30)),
                ('description', models.TextField()),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.subject')),
            ],
        ),
    ]
