# Generated by Django 5.2.6 on 2026-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='branch',
        ),
        migrations.AddField(
            model_name='batch',
            name='current_semester',
            field=models.CharField(default='Sem1', max_length=10),
        ),
    ]
