# Generated by Django 5.2.6 on 2026-03-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_faculty_branch_batch_current_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
